name: Release Draft ðŸš€
on:
  push:
    tags:
      - 'v*'

jobs:
  publishGitRelease:
    if: startsWith(github.ref, 'rrefs/heads/release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:  dist/*
          draft: true
          fail_on_unmatched_files: true